### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by adfranse2** [devjetsoftware/docinsight-support#14]
* mark only the installed delphi versions 
* Install only the selected version on the system (6.0.0.6 installs docinsight210.bpl .. docinsight290.bpl )

**Comment by adfranse2** [comment]
Sign setup.exe

**Comment by zuobaoquan** [comment]
> * mark only the installed delphi versions
> * Install only the selected version on the system (6.0.0.6 installs docinsight210.bpl .. docinsight290.bpl )

That make sense. I have also reorganized the components. It will select the extensions for installed Delphi IDEs by default.

![components](https://github.com/devjetsoftware/docinsight-support/assets/740504/b7238f91-6c3d-4783-9b2f-18b6fa58b6a5)

**Comment by zuobaoquan** [comment]
> Sign setup.exe

I'm about to create a dedicated issue for the code signing.
